/**
 * Downloads the webfonts into public/fonts and writes src/styles/fonts.css.
 *
 * Self-hosted rather than loaded from fonts.googleapis.com: that put the
 * visitor's IP in front of Google before any consent was given, and cost two
 * extra connections on the critical path.
 *
 * Only the latin and latin-ext subsets are kept. Portuguese accents all live
 * in latin (U+0000-00FF), so in practice a visitor downloads only that.
 */
import { writeFileSync, mkdirSync } from "node:fs";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";
const SRC =
  "https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,320..560;1,9..144,320..500&family=Inter:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap";
const KEEP = new Set(["latin", "latin-ext"]);

mkdirSync("public/fonts", { recursive: true });

const css = await (await fetch(SRC, { headers: { "User-Agent": UA } })).text();
const blocks = [...css.matchAll(/\/\* (\S+) \*\/\s*(@font-face \{[^}]*\})/g)];
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

const seen = new Map();
const out = [];
let total = 0;

for (const [, subset, block] of blocks) {
  if (!KEEP.has(subset)) continue;
  const family = /font-family: '([^']+)'/.exec(block)[1];
  const style = /font-style: (\w+)/.exec(block)[1];
  const weight = /font-weight: ([^;]+)/.exec(block)[1].trim().replace(/\s+/g, "-");
  const url = /src: url\((https:[^)]+)\)/.exec(block)[1];

  const key = `${slug(family)}-${subset}-${style}-${weight}`;
  const i = seen.get(key) || 0;
  seen.set(key, i + 1);
  const name = i ? `${key}-${i}.woff2` : `${key}.woff2`;

  const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
  writeFileSync(`public/fonts/${name}`, buf);
  total += buf.length;
  out.push(block.replace(/src: url\(https:[^)]+\)/, `src: url('/fonts/${name}')`));
}

const header = `/*
 * Self-hosted webfonts. Generated by scripts/fetch-fonts.mjs — do not edit.
 * Regenerate with: npm run fonts
 */

`;
writeFileSync("src/styles/fonts.css", header + out.join("\n\n") + "\n");
console.log(`${out.length} files, ${Math.round(total / 1024)}KB`);
